### ISSUE TITLE
Replacing certain network's convolutions with WTConv actually resulted in a decrease in the metric.

### ISSUE THREAD

**Issue by 18188110239** [BGU-CS-VIL/WTConv#37] opened 2024-12-23 04:17 UTC
Dear Sir, thank you for your great contribution. I have some questions, please kindly answer them.
Replacing certain network's convolutions with WTConv actually resulted in a decrease in the metric.
I replaced the convolution operation in WTConv with UKAN's convolution operation, but the IoU metric for segmentation actually decreased. What could be the reason for this?

**Comment by shahaffind** [comment] 2024-12-23 07:15
Can you share the modified code?

**Comment by 18188110239** [comment] 2024-12-23 07:39
Dear sir, thank you for taking time out of your busy schedule to answer my question. I think wtconv is a good method to replace depthwise separable conv, and I have made good improvements in many experiments. However, some network models have achieved good results in the early stage, but the indicators will decline after a certain number of rounds. I have tried to adjust the wavelet type, including the number of wavelet decomposition wt_levels, but the effect cannot be improved. Here are some of my codes.

 I replaced the convolution part with wtconv_block

```
class WTConv_block(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=5,stride=1,wt_levels=3):
        super().__init__()

        self.depthwise = WTConv2d(in_channels, in_channels, kernel_size=kernel_size,wt_levels=wt_levels)
        self.pointwise = nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=stride, padding=0, bias=False)

    def forward(self, x):
        x = self.depthwise(x)
        x = self.pointwise(x)
        return x
```

The complete code is defined here： [WTUKAN](https://github.com/18188110239/WTUKAN/blob/main/archs.py)
      
I am exploring the lesion segmentation of ICH's CT or MRI, and I very much hope that wtconv can play a good role in my project. Thank you again for your contribution!

**Comment by shahaffind** [comment] 2024-12-23 14:34
There might be parts where the WTConv is suboptimal (patch embedding for example, which is usually not done using the separable operation)

In general, you can you try to replace it in parts (first encoder, then decoder, etc) and see how it works.
Also you are using 7-8 levels of WT decomposition, you can try to use a lower number first (3-5) and see if it works better

**Comment by 12138wa** [comment] 2024-12-26 07:56
Dear Sir, thank you for your great contribution. I have some questions, please kindly answer them.
I encountered the following issues while reproducing your work wtconvnext_tiny train.
Traceback (most recent call last):
  File "train.py", line 1181, in <module>
    main()
  File "train.py", line 559, in main
    optimizer = create_optimizer_v2(
  File "/home/dl/anaconda3/envs/wtconv/lib/python3.8/site-packages/timm/optim/optim_factory.py", line 235, in create_optimizer_v2
    parameters = param_groups_layer_decay(
  File "/home/dl/anaconda3/envs/wtconv/lib/python3.8/site-packages/timm/optim/optim_factory.py", line 108, in param_groups_layer_decay
    no_weight_decay_list = set(no_weight_decay_list)
TypeError: 'NoneType' object is not iterable.What could be the reason for this?

**Comment by shahaffind** [comment] 2024-12-30 04:46
Hi @12138wa,
This is not related to this issue, please open a new one next time.
This issue was brought up before and was closed by the one who opened it, maybe he has the answer as I was unable to reproduce this error.

You can open a new issue with more information (all the installed packages and whatever else you think can help me reproduce the error)

**Closed by shahaffind** 2024-12-30 04:46 UTC
