### ISSUE TITLE
Why print some irrelevant information? [ torch.cuda.FloatTensor{480,1,2,2} ]

### ISSUE THREAD

**Issue by BigworldNebula** [BGU-CS-VIL/WTConv#27] opened 2024-11-06 04:44 UTC
**Thanks to the author for his great contribution.**
When I am currently using **WTConv2d**, the following information appears, resulting in overwriting useful output information content. I tried to find the printout code in **WTConv2d**, but it was not found.
**Looking forward to your reply.**

**Omit here...**
(472,1,.,.) =
  0.5000 -0.5000
 -0.5000  0.5000

(473,1,.,.) =
  0.5000  0.5000
  0.5000  0.5000

(474,1,.,.) =
  0.5000  0.5000
 -0.5000 -0.5000

(475,1,.,.) =
  0.5000 -0.5000
  0.5000 -0.5000

(476,1,.,.) =
  0.5000 -0.5000
 -0.5000  0.5000

(477,1,.,.) =
  0.5000  0.5000
  0.5000  0.5000

(478,1,.,.) =
  0.5000  0.5000
 -0.5000 -0.5000

(479,1,.,.) =
  0.5000 -0.5000
  0.5000 -0.5000

(480,1,.,.) =
  0.5000 -0.5000
 -0.5000  0.5000
[ torch.cuda.FloatTensor{480,1,2,2} ]

**Comment by shahaffind** [comment] 2024-11-06 13:05
Hey, there are no print commands in the code. Maybe it's related to the codebase you are using the layer in?

**Comment by shahaffind** [comment] 2024-11-13 09:24
I just wanted to let you know I'm closing this issue for now. Please reopen it if the problem is still there

**Closed by shahaffind** 2024-11-13 09:24 UTC
